coverage:
  # number of digits after decimal point
  precision: 2
  # round coverage value down to `precision`
  round: down

  status:
    # master coverage
    project:
      default:
        # auto: use coverage from base commit
        target: auto
        # Allow coverage to drop by the following and still be success
        threshold: 1%

    # PR coverage
    patch:
      default:
        target: auto
        threshold: 1%

# Ignore these paths when calculating the coverage
ignore:
  - "pydicom/tests"
  - "pydicom/benchmarks"

# Pull request comments, use `comment: off` to disable
comment:
  # header: default message header?, diff: the coverage diff of the PR
  layout: "header, diff"
  # update the PR comment if it exists, otherwise post a new comment
  behavior: default
  # Always post a comment even if the coverage doesn't change
  require_changes: no
  # Post comment even if no coverage report for head exists
  require_head: no
  # Post comment even if no coverage report for base exists
  require_base: no
