#!/bin/bash
# all.sh
echo shell_all
echo run pydicom test suite on all supported python versions
echo ------- python 2.6 ------------
python2.6 run_tests.py
echo ------- python 2.7 ------------
python2.7 run_tests.py

# Check location for each version -- to make sure are not running old pydicom versions
echo -
echo -----------------
echo Check locations, make sure not pointing to old pydicom code:
echo Python 2.6
python2.6 -c "import dicom;print dicom.__file__"
echo Python 2.7
python2.7 -c "import dicom;print dicom.__file__"
