# Copyright 2020 pydicom authors. See LICENSE file for details.

import numpy as np

from pydicom.dataset import Dataset
from pydicom.uid import UID


def is_available() -> bool: ...

def supports_transfer_syntax(tsyntax: UID) -> bool: ...

def needs_to_convert_to_RGB(ds: Dataset) -> bool: ...

def should_change_PhotometricInterpretation_to_RGB(ds: Dataset) -> bool: ...

def as_array(ds: Dataset) -> np.ndarray: ...

def generate_frames(ds: Dataset, reshape: bool = True) -> np.ndarray: ...

def get_pixeldata(ds: Dataset) -> np.ndarray: ...
