name: tests

on:
  workflow_call:
    inputs:
      os:
        required: true 
        type: string
      python-version:
        required: true 
        type: string
      do-coverage:
        required: false
        type: boolean


env:
  PYTEST_ARGS: --cov-append --cov=pydicom

jobs:
  tests:
    runs-on: ${{ inputs.os }}-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip

    - name: Install pydicom and tools  # not 'editable install'
      run: |
        python -m pip install .[dev]

    - name: Test without numpy or handlers
      run: |
        python -m pytest --cov-reset ${{ env.PYTEST_ARGS }}

    - name: Test with Numpy
      run: |
        python -m pip install .[basic]
        python -m pytest ${{ env.PYTEST_ARGS }} 

    - name: Test with all optional dependencies
      run: |
        python -m pip install .[pixeldata,gpl-license]
        python -m pytest ${{ env.PYTEST_ARGS }} 
    
    - name: Full coverage
      if: inputs.do-coverage
      # A small number of tests only run if libs missing
      run: |
        python -m pip uninstall -y pylibjpeg pydicom_data
        python -m pytest ${{ env.PYTEST_ARGS }}

    - name: Send coverage results
      if: success() && inputs.do-coverage
      uses: codecov/codecov-action@v3
